version: '3'
services:
  jupyterlab:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    image: utfpr/jupyterlab
    ports:
      - "10000:8888"
      - "4040:4040"
    volumes:
      - /work/master-thesis/notebooks:/opt/work/notebooks/
      - /work/datalake:/opt/work/data/
