version: '2.1'
services:
  spark-master:
    image: altr/spark
    container_name: spark-master
    ports:
      - "8088:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./data-processing:/data-processing
      - /work/datalake:/data
  spark-worker-1:
    image: altr/spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8089:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./data-processing:/data-processing
      - /work/datalake:/data
