- dag_id: download_files
  name: Download and Decompress Files
  description: Download files for processing
  owner: airflow
  depend_on_past: False
  email_on_failure: False
  email_on_retry: False
  retries: 1

